name: Check for new tags
on:
  schedule:
    - cron: "* * * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tags
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            curl https://api.github.com/repos/getlago/lago-openapi/git/refs/tags | jq  -r .[].ref
