name: Build OpenAPI Lago Client

on:
  push:
    branches:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'v*.*.*'

jobs:
  generate-php-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI PHP Client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Lago PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/getlago/lago-openapi/${GITHUB_REF_SLUG}/openapi.yaml
          command-args: "--additional-properties=invokerPackage=Lago\\Client -o ."
          
      - name: Auto-Heal composer.json
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            jq ".name = \"$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')\"" composer.json > composer.json.tmp
            mv composer.json.tmp composer.json
          
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          fetch: false
          message: "Update Lago PHP CLient ${GITHUB_REF_SLUG}"
          tag: "${GITHUB_REF_SLUG} --force"
          tag_push: '--force'
